[versions]
zstd = "1.5.7-6"
paperweight = "2.0.0-beta.19"
run = "3.0.0"
resource = "1.3.1"
minecraft = "1.21.10"
hangar-publish = "0.1.3"

[libraries]
zstd = { module = "com.github.luben:zstd-jni", version.ref = "zstd" }

[plugins]
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
run = { id = "xyz.jpenilla.run-paper", version.ref = "run" }
resource-paper = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "resource" }
hangar-publish = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar-publish" }